### PR TITLE
working on LFA feed back

### PR DESCRIPTION
**Pull request by JamesMudidi**
Good evening KLA Bootcamp 15,

Kindly take some time off your busy schedule and review the changes I have made and leave feedback.

@solnsubuga @3Nakajugo @StephenCMwanika @bashman1 @NicholusMuwonge @66hakeem @Phionanamugga @engjames @Paphra @digit2018 @BrunoNicholas @edrinesolo @astonetuhame @jngisiro @Hassan-Ssemanda @Emmanuelaaron @alexxsanya @dkato8181 @AbuDeCoder @Nico-Nsereko @alinitweSandra @daspro1503 @ivankfit @ asimwec @brucenelm @sebbss @Rhytah @llwasampijja @musasizifrancis @RachealN @nearjay06 @mderek227 @sanya-kenneth @neelxie @frankopkusianwar @AtamaZack @ManuelDominic @KabohaJeanMark @mwinel @chrismatgit @ringtho @nadralia @Kwandera @JammyKalungi @reifred @jennizalwango @jkMugabe @richien @Araali1 @Mastula77 @Genza999 @wabuluka @noahkalyesubula @lizz24 @kalsmic @k7ko @bekeplar @e-ian @masete @Manorlds-Eaglespark @nanfuka @HarrietAkot @PatrickMugayaJoel @kyakusahmed @Anguandia @CandySusan @kabaliisa @bisonlou @HabibSentongo @v1b3m @kdenno @davicken @dtnnml @Araali1 @natalie-abbie @ernesthenry

### CODE REVIEW

**Comment by bekeplar** [comment]
Consider removing your test data inside your tests and put them into the SetUp

**Comment by JamesMudidi** [comment]
> Consider removing your test data inside your tests and put them into the SetUp

Thanks for the feedback Joseph

**Comment by mwinel** [comment]
Next time briefly describe what your PR does it gives the reviewers a brief background of what your code changes are about. This way people get a clear view of how to respond back.

**Comment by llwasampijja** [comment]
Good work @JamesMudidi 
In Python, snake_case naming convention is preferred to camelCase when naming variables
You should handle some of the site errors like not found and 500 internal server error.
It would be better if in your readme or response error messages you let the user know all the fields required for a successful post

**Comment by JamesMudidi** [comment]
> Next time briefly describe what your PR does it gives the reviewers a brief background of what your code changes are about. This way people get a clear view of how to respond back.

Thanks, @mwinel for the feedback. will do that next time

**Comment by JamesMudidi** [comment]
> Good work @JamesMudidi
> In Python, snake_case naming convention is preferred to camelCase when naming variables
> You should handle some of the site errors like not found and 500 internal server error.
> It would be better if in your readme or response error messages you let the user know all the fields required for a successful post

Thanks, @llwasampijja for the feedback. let me get on it

**Pull request merged**
